import assert from 'node:assert/strict';
import { Flight, bombStep } from '../physics.js';
import * as THREE from '../vendor/three.module.js';

const dt=1/120;
function simulate(f,seconds,input){for(let t=0;t<seconds;t+=dt)f.step(dt,typeof input==='function'?input(f,t):input);}
const f=new Flight();
simulate(f,12,{throttle:1});
assert(f.grounded&&!f.crashed,'Must stay on runway without rotation');
const runwaySpeed=f.velocity.length();
simulate(f,14,f=>({throttle:1,pitch:f.velocity.length()>74?(f.basis().forward.y<.13?.5:0):0}));
assert(!f.grounded&&!f.crashed&&f.position.y>25,'Must take off with deliberate rotation');
console.log('PASS takeoff',JSON.stringify({runwaySpeed,altitude:f.position.y,speed:f.velocity.length(),z:f.position.z}));
const b={position:new THREE.Vector3(0,300,0),velocity:new THREE.Vector3(0,0,-130)};
let impactTime=0;for(;impactTime<20;impactTime+=dt)if(bombStep(b,dt))break;
assert(impactTime>7&&impactTime<9&&b.position.z<-900,'Bomb must fall ballistically and retain forward velocity');
console.log('PASS ballistic bomb',JSON.stringify({impactTime,downrange:-b.position.z}));
const land=new Flight();land.position.set(0,5,-100);land.velocity.set(0,-2,-82);land.grounded=false;land.airborneTime=60;land.attitude.setFromEuler(new THREE.Euler(.08,0,0));land.spool=land.throttle=.25;
simulate(land,3,{brake:true});
assert(land.landed&&!land.crashed,'A gentle geared touchdown on runway must survive');
simulate(land,20,{brake:true,throttle:-1});
assert(land.velocity.length()<1,'Wheel brakes must stop the aircraft');
console.log('PASS touchdown and braking');
const bad=new Flight();bad.position.set(0,3,-100);bad.velocity.set(0,-12,-85);bad.grounded=false;bad.gear=false;bad.gearPosition=0;
simulate(bad,1,{});assert(bad.crashed,'Hard belly impact must fail');console.log('PASS hard landing rejection');
const a=new Flight(),c=new Flight();simulate(a,8,{throttle:1});for(let i=0;i<8*60;i++)c.step(1/60,{throttle:1});
assert(a.position.distanceTo(c.position)<2,'Physics must be stable across frame rates');console.log('PASS timestep stability');
const turn=new Flight();turn.position.set(0,1000,0);turn.velocity.set(0,0,-165);turn.grounded=false;turn.gear=false;turn.gearPosition=0;turn.throttle=turn.spool=.55;
const initialDirection=turn.velocity.clone().normalize();
simulate(turn,.25,{roll:.8});
const initialTurn=turn.velocity.clone().normalize().angleTo(initialDirection);
assert(initialTurn<.02,'Roll input must not instantly rotate the flight path');
simulate(turn,1,{roll:.65});
simulate(turn,10,{pitch:.17});
const finalTurn=turn.velocity.clone().normalize().angleTo(initialDirection);
assert(finalTurn>.15&&!turn.crashed,'Banked lift must turn the aircraft progressively');
console.log('PASS inertial banked turn',JSON.stringify({initialDegrees:initialTurn*180/Math.PI,finalDegrees:finalTurn*180/Math.PI,altitude:turn.position.y}));
const slow=new Flight();slow.position.set(0,600,0);slow.velocity.set(0,0,-40);slow.grounded=false;slow.gear=false;slow.gearPosition=0;
simulate(slow,4,{pitch:1});
assert(slow.position.y<575&&slow.velocity.y<0,'A slow aircraft must lose height even with aft stick');
console.log('PASS low-speed energy loss');
